# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {}

modules = []

doc_url = "https://rosejb.github.io/bdl_exporter/"

git_url = "https://github.com/rosejb/bdl_exporter/tree/master/"

def custom_doc_links(name): return None
